app/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('user/', include('users.urls', namespace='user')),
    path('courses/', include('courses.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
    
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from main import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('gallery/', views.gallery, name='gallery'),
    path('feedback/', views.feedback, name='feedback'),
    path('feedback/success/', views.feedback_success, name='feedback_success'),
    path('reviews/', views.reviews, name='reviews'),
    path('contacts/', views.contacts, name='contacts'),


]

users/urls.py
from django.urls import path
from users import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'users'

urlpatterns = [
    path('profile/signup/', views.signup_user, name='signup'),
    path('profile/login/', views.login_user, name='login'),
    path('profile/logout/', views.logout_user, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('profile/create-review/', views.create_review, name='create_review'),
    path('exam/', views.exam_view, name='exam'),
    path('upload-avatar/', views.upload_avatar, name='upload_avatar'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{title}}</title>
    {% block css_about %} {% endblock css_about %}
    {% block css_modules %} {% endblock %}

    {% block css_gallery%} {% endblock css_gallery %}
    {% block css_reviews%} {% endblock css_reviews %}


    <link rel="stylesheet" href="{% static 'deps/css/button.css' %}">
    <link rel="stylesheet" href="{% static 'deps/css/footer.css' %}">
    <link rel="stylesheet" href="{% static 'deps/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'deps/css/form.css' %}">
    <link rel="stylesheet" href="{% static 'deps/css/user.css' %}">
    <link rel="stylesheet" href="{% static 'deps/css/contacts.css' %}">
   
    <link rel="preload" href="{% static 'deps/fonts/Jost-Regular.woff2' %}" as="font" type="font/woff2" crossorigin>
    
    <script src={% static "deps/js/script.js" %} async></script>

</head>
<body>
    <header>
        <nav>
            <div class="logo"><a href="{% url 'main:index' %}">Цветочное Ателье</a></div>

    
            <button class="burger" id="burger">
                ☰
            </button>

            <ul class="menu" id="menu">
                <li><a href="{% url 'main:about' %}">О курсе</a></li>
                <li><a href="{% url 'main:gallery' %}">Галерея</a></li>
                <li><a href="{% url 'main:reviews' %}">Отзывы</a></li>
                <li><a href="{% url 'module_list' %}">Модули курса</a></li>
                <li><a href="{% url 'main:contacts' %}">Контакты</a></li>
                <li><a href="{% url 'users:exam' %}">Экзамен</a></li>
                <li><a href="{% url 'users:login' %}">Личный кабинет</a></li>
            </ul>

        
            <div class="buttons">
                <a href="{% url 'users:signup' %}" class="btn btn-purple">Зарегистироваться</a>
                <a href="{% url 'users:login' %}" class="btn btn-green">Войти</a>
            </div>
        </nav>
    </header>
    <main>
        {%block about%}{%endblock%}
        {%block works%}{%endblock%}
        {%block reviews%}{%endblock%}
        {%block login%}{%endblock%}
        {%block registration%}{%endblock%}
        {%block profile%}{%endblock%}
        {%block description %}{%endblock%}
        {%block gallery%}{%endblock%}
        {%block structure%}{%endblock%}
        {%block  teacher%}{% endblock%}

        {%block faq-container%}{%endblock%}
        {%block  modules%}{% endblock%}

        {% block module_1%}{% endblock%}
        {%block catalog%}{% endblock%}
        {%block lesson%}{% endblock%}
        {%block exam%}{% endblock%}
        {%block exam_suc%}{% endblock%}
        {% block exam_f %}{% endblock%}
        {% block contacts%}{% endblock%}
        {%block feedback%}{%endblock%}







       


    <footer class="footer">
        <div class="footer-container">
            <div class="footer-section">
                <h3>О нас</h3>
                <p>Приглашаем на курсы флористики и творческие мастер-классы в уютном пространстве, где рождаются красота и вдохновение.</p>
            </div>
            <div class="footer-section">
                <h3>Контакты</h3>
                <ul>
                    <li><a href="mailto:info@flowers.com">flowers.ulyanovsk@mail.ru</a></li>
                    <li><a href="tel:+1234567890">+7 (951) 092-49-60</a></li>
                    <li>г. Ульяновск, ул. Спасская, д. 12</li>
                </ul>
            </div>
            <div class="footer-section">
                <h3>Главная</h3>
                <ul class="social-links">
                    <li><a href="{%url "main:about" %}">О курсе</a></li>
                    <li><a href="{%url "main:gallery" %}">Галерея</a></li>
                    <li><a href="{%url "main:reviews" %}">Отзывы</a></li>
                    <li><a href="#">Модули курса</a></li>
                    <li><a href="{%url "users:login" %}">Личный кабинет</a></li>


                </ul>
            </div>
           
        </div>
        <div class="footer-bottom">
            <p>&copy; 2025 Цветочные секреты. Все права защищены.</p>
        </div>
    </footer>

    </main>


    
</body>
</html>